import React from 'react';
import {Grid, Row} from 'react-bootstrap/lib';

//component

import Quened from '../Quened/Quened'
import Planning from "../Planning/Planning";


const projects = [
  {
    type: "Mobile App",
    company: "Google",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Wordpress theme",
    company: "Google",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Mobile App",
    company: "Google",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New Logo",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Mobile App",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Google",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Google",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Mobile App",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Google",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Wordpress theme",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Google",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Mobile App",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New Logo",
    company: "Google",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Mobile App",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Mobile App",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Wordpress theme",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Mobile App",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New Logo",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Mobile App",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Mobile App",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Wordpress theme",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Mobile App",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New Logo",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/ava.png',
    id: "user1",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Mobile App",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Microsoft",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Landing page",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "New website",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/LyanRoach.png',
    id: "user3",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  },
  {
    type: "Dashboard",
    company: "Symu.co",
    price: "$1500",
    userImg: '/img/MichelleStewart.png',
    id: "user2",
    deadline: '15 May 2016',
    timeLeft: '10 days left',
    timeSpent: '40 hours',
    progress: 70,
    status: 'Development',
    assignedName: 'Dominic Lynton',
    assignedPosition: 'Front End Dev'
  }

];




class DNDWrap extends React.Component {

  render() {

    return (
      <div className="Workflow">

        <Grid fluid>
          <Row>
            <Quened/>
            <Planning/>
          </Row>
        </Grid>

      </div>
    )
  }
}

export default DNDWrap;